namespace: "maxbytes"
name: "omnikeeper"
version: "1.1.2"
readme: "README.md"
authors:
    - "Maximilian Csuk"
dependencies: {}
license:
    - Apache-2.0
tags:
    - collection
repository: "https://github.com/max-bytes/omnikeeper-ansible-collection"